### ISSUE TITLE
Resource Included in The Flask Community Workgroup

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [EwetoyeIbrahim/Flask-Marketplace#14]
Greetings,

The project has been added as a resource on the Flask Community Workgroup [resources](https://flaskcwg.github.io/resources/c/ecommerce/) section with data source [here](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/info.json#L180) in case you want to edit.

In the unfortunate case you project that you will no longer work on the project, you can request a take over from the workgroup by applying as defined [here](https://flaskcwg.github.io/takeover/). The WG has other ongoing initiatives which you can glean [here](https://flaskcwg.github.io/join/).

This issue is for information purposes only. You can close it after reading. For more suggestions write to flaskcwg at python dot org

**Comment by EwetoyeIbrahim** [comment]
🎉 🎉 🎉 
Thank you @Abdur-rahmaanJ,

I am very excited about this and it will serve as motivation to continue working on the project.

Thank you.
